### ISSUE TITLE
Error while parsing log

### ISSUE THREAD

**Issue by realAndrian** [danifischer/raidTimeline#1]
When i try to run the raidTimeline.exe from cmd the following two errors occur. The first appears when I try to load the logs through dpsReport and the second when I try to load local data.

C:\Users\User\Dokumente\Guild Wars 2\addons\raidTimeline>raidTimeline.exe -path "C:\LOG" -token "TokenID" -number 10
Loading log ...
Parsing log ...
Unhandled exception. System.FormatException: String '{{getLogData().encounterStart}}' was not recognized as a valid DateTime.
   at System.DateTime.ParseExact(String s, String format, IFormatProvider provider)
   at raidTimelineLogic.EiHtmlParser.SetTime(Action`1 setAction, String encounter, String startString) in D:\git\gw2\raidTimeline\raidTimelineLogic\EiHtmlParser.cs:line 44
   at raidTimelineLogic.EiHtmlParser.ParseLog(String filePath) in D:\git\gw2\raidTimeline\raidTimelineLogic\EiHtmlParser.cs:line 21
   at raidTimelineLogic.TimelineCreator.CreateTimelineFileFromWeb(String path, String outputFileName, String token, Int32 numberOfLogs) in D:\git\gw2\raidTimeline\raidTimelineLogic\TimelineCreator.cs:line 85
   at raidTimeline.Program.Main(String[] args) in D:\git\gw2\raidTimeline\raidTimeline\Program.cs:line 26

C:\Users\User\Dokumente\Guild Wars 2\addons\raidTimeline>raidTimeline.exe -path "C:\LOG"
Parsing log ...
Unhandled exception. System.FormatException: String '{{getLogData().encounterStart}}' was not recognized as a valid DateTime.
   at System.DateTime.ParseExact(String s, String format, IFormatProvider provider)
   at raidTimelineLogic.EiHtmlParser.SetTime(Action`1 setAction, String encounter, String startString) in D:\git\gw2\raidTimeline\raidTimelineLogic\EiHtmlParser.cs:line 44
   at raidTimelineLogic.EiHtmlParser.ParseLog(String filePath) in D:\git\gw2\raidTimeline\raidTimelineLogic\EiHtmlParser.cs:line 21
   at raidTimelineLogic.TimelineCreator.CreateTimelineFileFromDisk(String path, String outputFileName) in D:\git\gw2\raidTimeline\raidTimelineLogic\TimelineCreator.cs:line 30
   at raidTimeline.Program.Main(String[] args) in D:\git\gw2\raidTimeline\raidTimeline\Program.cs:line 33

**Comment by danifischer** [comment]
Hi,

can you send me the dps.report link to the log please.

---

Reminder to me: 
I currently assume that the timezone after the datetime is +/- 0 or the timeformat is different.

**Comment by danifischer** [comment]
EI Version: 2.26.0.0 changes something in the way the time is created. This breaks my tool.

**Comment by danifischer** [comment]
Fixed in verison 1.2.1: https://github.com/danifischer/raidTimeline/releases/tag/1.2.1
